name = "bucketdrive-api"
main = "apps/api/src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "bucketdrive-db"
database_id = "4d32efe1-77cc-4963-a6e9-89187f97e2f7"
migrations_dir = "packages/shared/src/db/migrations"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "bucketdrive-db-staging"
database_id = ""
migrations_dir = "packages/shared/src/db/migrations"

[[env.production.d1_databases]]
binding = "DB"
database_name = "bucketdrive-db"
database_id = ""
migrations_dir = "packages/shared/src/db/migrations"

# R2 Buckets
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "nekomatadrive"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "bucketdrive-staging"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "bucketdrive-files"

# Environment Variables
[vars]
APP_URL = "http://localhost:5173"
API_URL = "http://localhost:8787"

[env.staging.vars]
APP_URL = "https://staging.bucketdrive.dev"
API_URL = "https://staging-api.bucketdrive.dev"

[env.production.vars]
APP_URL = "https://drive.nekomata.moe"
API_URL = "https://drive.nekomata.moe/api"

# Workers (background jobs)
[env.production.workers]
name = "bucketdrive-workers"
main = "apps/workers/src/index.ts"
